# A test stage that will run the tests for the frontend (use npm run test) and for the backend (use python -m pytest).
# A build stage that will build Docker images for both frontend and backend

stages:
  - test
  - build

services:
  - docker:dind

test_frontend:
  stage: test
  image: node:20
  script:
    - cd client
    - npm install
    - echo "Running frontend tests"
    - npm run test
  only:
    - main

test_backend:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - cd server
    - echo "Running backend tests"
    - python -m pytest
  only:
    - main

build_frontend:
  stage: build
  script:
    - cd client
    - echo "Building frontend Docker image"
    - docker build . -t client
  only:
    - main
  needs:
    - test_frontend # Build stage depends on test_frontend job

build_backend:
  stage: build
  script:
    - cd server
    - echo "Building backend Docker image"
    - docker build . -t backend
  only:
    - main
  needs:
    - test_backend # Build stage depends on test_backend job
