apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https

  selector:
    app: caddy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: "caddy:alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /data/
              name: caddycerts
      volumes:
        - name: caddycerts
          hostPath:
            path: "/run/desktop/mnt/host/c/Users/KIIT/Documents/Github/devops-code-challenge-tsc-2024/development-certs"
